on:
  workflow_dispatch:
    inputs:
      instance:
        type: choice
        description: Instance
        options:
          - one
          - two

permissions:
  contents: read
  pull-requests: write

env:
  instance: ${{ inputs.instance }}
  email: "${{ ({ 'inaas7': 'hello@example.com'})[github.actor] }}"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$instance with $email" >> $GITHUB_STEP_SUMMARY
