on:
  workflow_dispatch:
    inputs:
      instance:
        type: choice
        description: Instance
        options:
          - one
          - two

permissions:
  contents: read
  pull-requests: write

env:
  instance: ${{ inputs.instance }}
  map: >-
    {
      "inaas7": "hello@example.com",
      "jsoref": "word@example.com",
      "": "add-additional-entries-above-this-entry@example.com"
    }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "$instance with $email" >> $GITHUB_STEP_SUMMARY
            echo "email=$email" >> $GITHUB_ENV
        env:
          email: ${{fromJSON(env.map)[github.actor]}}
      - run: echo "hello $email" >> $GITHUB_STEP_SUMMARY
